### ISSUE TITLE
Roadmap for final V1

### ISSUE THREAD

**Issue by beatrizmilz** [thiago-goncalves-souza/zootraits#6]
# General
- [x] Rename the pages
- [x] Add section about license 
```
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
```

- [x] [Fix with suggestions from the team](https://github.com/beatrizmilz/zootraits/issues/6#issuecomment-1712653987)

# Contribute

- [ ] One more round of testing, now with real data (@thiago-goncalves-souza 's team)
- [x] Finish the back-end with GitHub Actions - update feedtrait

# Deploy
- [x] Transfer the repository to Thiago (or a GitHub org from the lab)
- [x] Deploy the app in another account (mind the name of the account, it will be in the URL)

- In order to do this tasks, it would be good if we make a video call

# Best do

- [ ]  ~add ORCID/GOOGLE SCHOLAR/homepage in the team dataset @thiagotoyoyo [by 15 de junho]~
- [ ] ~Thiago's team is going to complete the lat/long and send the updated dataset~
- [x] Thiago's team review information on metadata
